name := StackCounter

G4TARGET := $(name)
G4EXLIB := true
CPPFLAGS += -std=c++11 

.PHONY: all
all: lib

include $(GAMOSINSTALL)/config/binmake.gmk
include $(GAMOSINSTALL)/config/general.gmk

include $(GAMOSINSTALL)/config/gamos_libraries.gmk

